@BASE_URL=http://localhost:3000/api

GET {{BASE_URL}}

###
GET {{BASE_URL}}/users

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name":"erdal",
    "userName":"muqoner3",
    "email":"easlanci3@gmail.com",
    "password":"1234567"
}

###
PATCH {{BASE_URL}}/users/6232511514992640bcb3433e
Content-Type: application/json

{
    "name":"serhat",
    "userName":"muqoner3"
}

###
DELETE {{BASE_URL}}/users/6233a5eb294c5637206bbe53





